default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: cafezim

development:
  <<: *default
  database: progas_development

test:
  <<: *default
  database: progas_test

production:
 adapter: postgresql
 encoding: unicode
 url: <%= ENV['gsystem'] %>
 encoding: unicode
 pool: 5
